INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('pro-tools-105hd', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('jd2-model-32', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('roguefab-m600-series', NULL, NULL, NULL, NULL, NULL, '.875', 'Mild steel, 4130 chromoly, Aluminum, Stainless steel, Titanium', NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, TRUE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('baileigh-rdb-250', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('baileigh-rdb-050', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('jd2-model-32-hydraulic', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('woodward-fab-wfb2', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Aluminum', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('jmr-tbm-250r-raceline', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum, Stainless Steel', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('jmr-tbm-250-ultra', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum, Stainless Steel', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('pro-tools-brute', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum, Stainless Steel', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('mittler-bros-2500', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('hossfeld-no2', NULL, NULL, NULL, NULL, NULL, NULL, 'Mild Steel, Chromoly, Aluminum, Flat Bar, Angle Iron', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('swag-offroad-rev2', NULL, NULL, NULL, NULL, NULL, '.25', 'Round Tube, DOM Tubing, Chromoly', NULL, 'None', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('roguefab-m601', 4, 5, 2, 3, 'portable_with_rolling_option', '.156', 'Mild steel, Stainless steel, 4130 chromoly, Aluminum, Titanium, Copper, Brass', 'Round tube, Square tube, EMT, Metric round / square, Plastic / urethane pressure dies, Other, Pipe', 'bronze', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('roguefab-m605', NULL, NULL, NULL, NULL, NULL, '.875', 'Mild steel, Stainless steel, 4130 chromoly, Brass, Copper, Titanium, Aluminum', 'Round tube, Pipe, Square tube, EMT, Metric round / square, Plastic / urethane pressure dies, Other', 'bronze', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;

INSERT INTO bender_overlays ("product_id", "usa_manufacturing_tier", "origin_transparency_tier", "single_source_system_tier", "warranty_tier", "portability", "wall_thickness_capacity", "materials", "die_shapes", "mandrel", "has_power_upgrade_path", "length_stop", "rotation_indexing", "angle_measurement", "auto_stop", "thick_wall_upgrade", "thin_wall_upgrade", "wiper_die_support", "s_bend_capability") VALUES ('roguefab-m625', NULL, NULL, NULL, NULL, NULL, '.875', NULL, 'Round tube, Pipe, Square tube, EMT, Metric round / square, Plastic / urethane pressure dies, Other', 'bronze', TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE)
ON CONFLICT (product_id) DO UPDATE SET
  usa_manufacturing_tier = EXCLUDED.usa_manufacturing_tier,
  origin_transparency_tier = EXCLUDED.origin_transparency_tier,
  single_source_system_tier = EXCLUDED.single_source_system_tier,
  warranty_tier = EXCLUDED.warranty_tier,
  portability = EXCLUDED.portability,
  wall_thickness_capacity = EXCLUDED.wall_thickness_capacity,
  materials = EXCLUDED.materials,
  die_shapes = EXCLUDED.die_shapes,
  mandrel = EXCLUDED.mandrel,
  has_power_upgrade_path = EXCLUDED.has_power_upgrade_path,
  length_stop = EXCLUDED.length_stop,
  rotation_indexing = EXCLUDED.rotation_indexing,
  angle_measurement = EXCLUDED.angle_measurement,
  auto_stop = EXCLUDED.auto_stop,
  thick_wall_upgrade = EXCLUDED.thick_wall_upgrade,
  thin_wall_upgrade = EXCLUDED.thin_wall_upgrade,
  wiper_die_support = EXCLUDED.wiper_die_support,
  s_bend_capability = EXCLUDED.s_bend_capability;
